### ISSUE TITLE
请问pycharm中如何导入gi，os等依赖库，目前在pycharm中运行hello.py报错。

### ISSUE THREAD

**Issue by zhengdeding** [geniusnut/ofd2img#1]
请问pycharm中如何导入gi，os等依赖库，目前在pycharm中运行hello.py报错。

![image](https://user-images.githubusercontent.com/18633371/93781994-98dc8100-fc5c-11ea-9f59-dfd2c999afed.png)

import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

window = Gtk.Window(title="Hello World")
window.show()
window.connect("destroy", Gtk.main_quit)
Gtk.main()

C:\msys64\mingw64\bin\python3.8.exe C:/msys64/home/zhengdeding/hello.py
Traceback (most recent call last):
  File "C:/msys64/home/zhengdeding/hello.py", line 4, in <module>
    import gi
  File "C:\msys64\mingw64\lib\python3.8\site-packages\gi\__init__.py", line 42, in <module>
    from . import _gi
ImportError: DLL load failed while importing _gi: 找不到指定的程序。

Process finished with exit code 1

**Comment by Zeelong** [comment]
请问你解决了吗
